# Generated by Django 4.0.6 on 2022-07-13 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thumb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_image', models.ImageField(default='none.png', null=True, upload_to='thumb/%Y/%m/%d')),
                ('left_image', models.ImageField(blank=True, upload_to='thumb/%Y/%m/%d')),
                ('back_image', models.ImageField(blank=True, upload_to='thumb/%Y/%m/%d')),
                ('right_image', models.ImageField(blank=True, upload_to='thumb/%Y/%m/%d')),
            ],
            options={
                'verbose_name_plural': '썸네일 이미지',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('model_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True)),
                ('price', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.thumb')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at', 'name'],
            },
        ),
    ]
