# Generated by Django 4.0.6 on 2022-07-13 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='category/%Y/%m/%d')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category')),
            ],
            options={
                'verbose_name_plural': '카테고리',
                'ordering': ['name', 'parent'],
            },
        ),
    ]
